#   Copyright 2023 natinusala
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

[class]
location = "package:flutter/material.dart"

[[parameter]]
name = "primarySwatch"
type = "MaterialColor?"
dart_named = true

[[property]]
name = "textTheme"
init_type = "TextTheme?"
type = "TextTheme"
default_value = "nil"
dart_named = true

[[property]]
name = "scaffoldBackgroundColor"
type = "Color"
init_type = "Color?"
dart_named = true
default_value = "nil"

[[property]]
name = "hintColor"
type = "Color"
init_type = "Color?"
dart_named = true
default_value = "nil"

[[property]]
name = "primaryTextTheme"
type = "TextTheme"
init_type = "TextTheme?"
dart_named = true
default_value = "nil"
